from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List

from .models import CaseSpec


def write_manifest(gallery_dir: Path, entries: List[Dict[str, Any]], coverage: Dict[str, Any] | None = None) -> None:
    manifest = {
        "schema_version": "rtm-gallery-v0",
        "coordinate_unit": "pdf_pt",
        "coordinate_origin": "top-left",
        "coverage_summary": coverage or {},
        "cases": entries,
    }
    (gallery_dir / "MANIFEST.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def write_index(gallery_dir: Path, cases: List[CaseSpec]) -> None:
    lines = [
        "# PDF Y-Band Picker RTM Gallery",
        "",
        "This gallery is generated by the deterministic RTM factory. Fill the review columns manually before freezing cases.",
        "",
        "| case_id | thumbnail | axis tags | realism 1-5 | keep/drop | critique |",
        "|---|---|---|---|---|---|",
    ]
    for case in cases:
        png_rel = f"{case.case_id}/{case.case_id}.p01.png"
        axes = ", ".join(f"{k}={v}" for k, v in case.axes.items())
        lines.append(f"| `{case.case_id}` | ![]({png_rel}) | {axes} |  |  |  |")
    (gallery_dir / "index.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
