"""Frozen fixture promotion (handoff T3 / D3).

Promotes human-kept candidate cases from the generated ``rtm_gallery`` into a
separate, durable ``rtm_frozen`` fixture set. The gallery is treated as
read-only; promotion is copy-only. Selection is driven by the ``keep/drop``
review column of ``rtm_gallery/index.md`` (case-insensitive ``keep``), with an
optional explicit ``--keep`` CLI override.

Promotion success is NOT detector correctness:

    promotion success != detector pass
"""
from __future__ import annotations

import json
import shutil
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

KEEP_VALUES = {"keep"}


class PromotionError(RuntimeError):
    """Raised for fail-safe conditions (empty selection, existing output, ...)."""


def parse_index_decisions(index_text: str) -> Dict[str, str]:
    """Parse the ``keep/drop`` column out of the gallery review table.

    Returns ``{case_id: raw_decision_string}`` for every data row. Header and
    separator rows are skipped. The table layout is:

        | case_id | thumbnail | axis tags | realism 1-5 | keep/drop | critique |
    """
    decisions: Dict[str, str] = {}
    for line in index_text.splitlines():
        line = line.strip()
        if not line.startswith("|"):
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        if len(cells) < 5:
            continue
        case_cell = cells[0].strip().strip("`").strip()
        if not case_cell or case_cell.lower() == "case_id":
            continue
        if set(case_cell) <= {"-", ":"}:  # separator row
            continue
        decisions[case_cell] = cells[4].strip()  # keep/drop column
    return decisions


def select_cases(
    manifest: Dict[str, Any],
    index_text: str,
    keep_override: Optional[List[str]],
) -> Tuple[List[str], List[str], str]:
    """Return (selected_ids, dropped_ids, selection_source)."""
    all_ids = [c["case_id"] for c in manifest.get("cases", [])]
    all_set = set(all_ids)
    if keep_override:
        unknown = [cid for cid in keep_override if cid not in all_set]
        if unknown:
            raise PromotionError(f"--keep lists unknown case_ids: {unknown}")
        keep_set = set(keep_override)
        selected = [cid for cid in all_ids if cid in keep_set]
        source = "cli"
    else:
        decisions = parse_index_decisions(index_text)
        selected = [cid for cid in all_ids if decisions.get(cid, "").strip().lower() in KEEP_VALUES]
        source = "index.md"
    dropped = [cid for cid in all_ids if cid not in set(selected)]
    return selected, dropped, source


def write_frozen_index(out_dir: Path, cases: List[Dict[str, Any]]) -> None:
    """Write a frozen *list* index.md (not a review form)."""
    lines = [
        "# RTM Frozen Fixtures",
        "",
        "Human-reviewed accepted fixtures promoted from the RTM gallery.",
        "Generated by promote_keep_cases.py — do not edit by hand.",
        "",
        "| case_id | axis tags | pages | pdf | truth |",
        "|---|---|---|---|---|",
    ]
    for c in cases:
        axes = ", ".join(f"{k}={v}" for k, v in c.get("axes", {}).items())
        cid = c["case_id"]
        lines.append(f"| `{cid}` | {axes} | {c.get('page_count', '')} | {cid}/{cid}.pdf | {cid}/{cid}.truth.json |")
    (out_dir / "index.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def promote(
    gallery_dir: Path | str,
    out_dir: Path | str,
    *,
    keep_override: Optional[List[str]] = None,
    force: bool = False,
    allow_empty: bool = False,
) -> Dict[str, Any]:
    """Promote kept gallery cases into a frozen fixture set.

    Raises PromotionError on fail-safe conditions. Never mutates ``gallery_dir``.
    """
    gallery_dir = Path(gallery_dir)
    out_dir = Path(out_dir)

    manifest_path = gallery_dir / "MANIFEST.json"
    if not manifest_path.exists():
        raise PromotionError(f"gallery MANIFEST.json not found: {manifest_path}")
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    index_path = gallery_dir / "index.md"
    index_text = index_path.read_text(encoding="utf-8") if index_path.exists() else ""

    selected, dropped, source = select_cases(manifest, index_text, keep_override)

    if not selected and not allow_empty:
        raise PromotionError(
            "no cases marked keep; refusing to create an empty frozen set "
            "(use --allow-empty to override)"
        )

    if out_dir.exists():
        if not force:
            raise PromotionError(f"output dir already exists: {out_dir} (use --force to overwrite)")
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True)

    by_id = {c["case_id"]: c for c in manifest.get("cases", [])}
    frozen_cases: List[Dict[str, Any]] = []
    for cid in selected:
        src = gallery_dir / cid
        if not src.is_dir():
            raise PromotionError(f"selected case directory missing in gallery: {src}")
        shutil.copytree(src, out_dir / cid)  # copy pdf + truth.json + notes.md + all PNGs
        frozen_cases.append(by_id[cid])

    frozen_manifest = {
        "schema_version": "rtm-frozen-v0",
        "source_gallery_schema_version": manifest.get("schema_version", "rtm-gallery-v0"),
        "coordinate_unit": manifest.get("coordinate_unit", "pdf_pt"),
        "coordinate_origin": manifest.get("coordinate_origin", "top-left"),
        "promotion": {
            "source_gallery": str(gallery_dir),
            "selection_source": source,
            "selected_count": len(selected),
            "dropped_count": len(dropped),
        },
        "cases": frozen_cases,
    }
    (out_dir / "MANIFEST.json").write_text(
        json.dumps(frozen_manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    write_frozen_index(out_dir, frozen_cases)

    return {
        "selected": selected,
        "dropped": dropped,
        "selection_source": source,
        "out_dir": str(out_dir),
        "manifest": frozen_manifest,
    }
